server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;

  location = /openapi.yaml {
    default_type text/yaml;
    try_files $uri =404;
  }

  location / {
    try_files $uri /index.html;
  }
}

